### ISSUE TITLE
Migrate to popper 2 or remove it

### ISSUE THREAD

**Issue by VincentLanglet** [weglot/design#62]
Popper.js est abandonné
https://www.npmjs.com/package/popper.js

Quelle est l'utilisation de cette lib ? Il faudrait la migrer ou la retirer.

Cela a été introduit ici https://github.com/weglot/design/commit/befad18be9125df05bb3738d06c94d04c1c51c75
par @floranpagliai ; une idée ?

**Comment by floranpagliai** [comment]
Deps de Bootstrap 4

**Comment by VincentLanglet** [comment]
Ok, donc faudra voir si bootstrap 4 marche avec la v2 de popper

**Comment by floranpagliai** [comment]
To do in #63
